### ISSUE TITLE
Config page

### ISSUE THREAD

**Issue by OmriLevy888** [OmriLevy888/song-tinder#9]
Config page for the app
- [x] Default playlist
- [x] Playlists shown when swiping up
- [x] Music source

Make all of these hard coded for now and just focus on the ability to change from a given source of inputs (playlists, sources...).

This page should be navigable from the main page using the bottom app bar (tab switch bar).

**Comment by shakedaes001** [comment]
Basic version. Will need to beautify and enhance later on.
